---
- hosts: jekyll
  tasks:
    - name: Install Ruby and dependencies
      apt: 
        name={{ item }}
        state=present
      with_items:
        - ruby2.0
        - ruby2.0-dev
        - libffi-dev 
        - libssl-dev
        - build-essential
        - nodejs

    - name: Install jekyll
      gem:
        name=jekyll
        state=present
        user_install=no
        executable=/usr/bin/gem2.0
      with_items:
        - jekyll

        # bundle install --system
        # - github-pages
        # - jekyll-paginate