---
# Base setup of the servers
- hosts: all
  roles:
    # Base setup
    - role: wcl-common
      common_users:
        - name: wcladmin
          sudo: yes
          ssh: yes
          authorized: "{{ wcladmin_ssh_pub_keys }}"

      disable_firewall: yes
      handle_firewall: false
      hostname: "{{ inventory_hostname }}.{{ internal_domain }}"

    # Install Wiredcraft custom monitoring scripts
    - role: wcl-zabbix-scripts
      # zabbix_nginx:
      #   url: http://localhost:8001/nginx_status
      #   nginxctl: /usr/sbin/nginx
      # zabbix_haproxy:
      #   stats_socket: /tmp/haproxy.zabbix

